application.yaml#spring:
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/forumalura?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: devjs

  jpa:
    database-plataform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: cd3f20d161832f
    password: 2ef198a7fc527d
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: secreto